### ISSUE TITLE
How To Install SetTimerService For Novices

### ISSUE THREAD

**Issue by bvallance** [temerkhanov/SetTimerService#1]
Hi temerkhanov.  I would like to use the SetTimeService in a Windows XP Professional VMWare virtual machine.  I have executed the SetTimeService.exe and the install_xp.cmd files, in that order.  I see the entry for the dependency on the SetTimerService in the registry for AudioSrv.  But there is no PlugPlay
RpcSsSetTimer service that has been installed in my Windows XP VM.  I'm not familiar with programming Windows services, so the files in your download don't mean anything to me (except the .exe and .cmd files).  What am I doing wrong?

**Comment by temerkhanov** [comment]
I've updated the Readme.md file. Please check.

**Comment by bvallance** [comment]
Thanks!

**Comment by ElecmanBricoman** [comment]
SetTimerService  bonsoir,

comment puije installer cette commande avec cmd svp aidez moi merci

**Comment by robross0606** [comment]
I'm so lost here.  Where do you even _find_ the SetTimeService.exe?  I don't see an available download.  Am I supposed to compile this myself?

**Comment by temerkhanov** [comment]
> I'm so lost here. Where do you even _find_ the SetTimeService.exe? I don't see an available download. Am I supposed to compile this myself?

The binary is in the Release directory
